config/routes.rb
TakeoutTerror::Application.routes.draw do

  get "establishments/show"
  get "establishments/index"

  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks',                                   :registrations      => "registrations"} 

  devise_scope :user do
    post '/users/new_with_omniauth' => 'users/omniauth_callbacks#new_with_omniauth', as: 'complete_user_registration_with_omniauth'
  end
  
  authenticated :user do
    get '/' => "users#show", as: "user_root"
  end
  
  resources :users, only: [:index, :show]
  get '/locations/ratings', to: 'locations#ratings'
  root to: "locations#initial_home"

  

end

app/models/badge.rb
class Badge < ActiveRecord::Base
  validates :name, presence: true
  validates :description, presence: true
  validates :type, presence: true

  def number_of_awards(user)
    raise NotImplementedError
  end
end

app/models/establishment.rb
class Establishment < ActiveRecord::Base
  
  has_many :visits, :inverse_of => :establishment
end

app/models/omniauth_identity.rb
class OmniauthIdentity < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook,:google_oauth2, :twitter]

  has_many :omniauth_identities, :dependent => :destroy
	
	has_many :visits, :inverse_of => :user
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :establishment
  belongs_to :user, :inverse_of => :visits
end

app/models/visits.rb
class Visits < ActiveRecord::Base
  belongs_to :user
  belongs_to :establishment
end

app/models/zero_rating_badge.rb
class ZeroRatingBadge < Badge

  def number_of_awards(user)
    user.visits.where(:fs_rating_value => 0).count > 0 ? 1 : 0
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_filter :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def after_sign_up_path_for(resource)
  	if resource.is_a?(User)
  		user_path(current_user)
  	end
  end

  def after_sign_in_path_for(resource)
  	if resource.is_a?(User)
  		user_path(current_user)
  	end
  end

  protected 

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation)}
  	devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password)}
  end	



end

app/controllers/establishments_controller.rb
class EstablishmentsController < ApplicationController

  def index
    @establishments = Establishment.all
    respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => @establishments }
    end
  end
  

  def show
    @establishment = Establishment.find(params[:id])
  end

end

app/controllers/locations_controller.rb
require 'rest_client'

class LocationsController < ApplicationController
  def ratings
    long = params[:long]
    lat = params[:lat]
    @response_xml = RestClient.get "http://ratings.food.gov.uk/enhanced-search/%5E/%5E/DISTANCE/0/%5E/#{long}/#{lat}/1/1000/json"
    render :inline => @response_xml
  end

  def initial_home
  	render 'initial_home'
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  # update the users details
  def update
    @user = User.find(current_user.id)
    successfully_updated = if needs_password?(@user, params)
      @user.update_with_password(devise_parameter_sanitizer.for(:account_update))
    else
      update_selected_attributes(params, @user)
    end
    
    if successfully_updated
      set_flash_message :notice, :updated
      # Sign in the user bypassing validation in case his password changed
      sign_in @user, :bypass => true
      redirect_to after_update_path_for(@user)
    else
      render "edit"
    end
  end


private
  
  # update only certain user attributes without exposure to mass assignment attack
  # (unlike the devise sanitizer no current password is required)
  def update_selected_attributes(params, user)
      name = params[:user][:name]
      password = params[:user][:password]
      password_confirmation = params[:user][:password_confirmation]

      user.name = name unless name.blank?
      user.password = password unless password.blank?
      user.password_confirmation = password_confirmation unless password_confirmation.blank?
      user.save
  end

  # check if we need password to update user data
  # ie if password or email was changed
  # extend this as needed
  def needs_password?(user, params)
    user.email != params[:user][:email]
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook; create; end
  def google_oauth2; create; end
  def twitter; create; end

  PROVIDERS = {
                'facebook'      => 'Facebook', 
                'google_oauth2' => 'Google',
                'twitter'       => 'Twitter'
              }

  def create
    auth = request.env["omniauth.auth"]
    email = auth[:extra][:raw_info][:email]
    @provider = auth.provider
    @uid = auth.uid
    name = auth.extra.raw_info.name

    omniauth_identity = OmniauthIdentity.where(:provider => @provider, :uid => @uid).first
    if omniauth_identity
      flash[:notice] = 'Signed in successfully via ' + PROVIDERS[@provider] + '.'
      sign_in_and_redirect(:user, omniauth_identity.user)
    elsif email != ''
      existing_user = User.find_by_email(email)
      if existing_user
        existing_user.omniauth_identities.create(:provider => @provider, :uid => @uid)
        flash[:notice] = 'Sign in via ' + PROVIDERS[@provider] + ' has been added to your account. Signed in successfully!'
        sign_in_and_redirect(:user, existing_user)
      else
        @user = User.new(name:name, email:email, password:Devise.friendly_token[0,20])
        begin
          @user.save!  
        rescue ActiveRecord::RecordInvalid
          render 'devise/registrations/new_with_omniauth'
          return
        end
        @user.omniauth_identities.create(:provider => @provider, :uid => @uid)
        flash[:notice] = 'Your account has been created via ' + PROVIDERS[@provider] + '. In your profile you can change your personal information and amend your local password from the one we have randomly generated for you.'
        sign_in_and_redirect(:user, @user)
      end
    else
      flash[:error] = PROVIDERS[@provider] + ' can not be used to sign-in as they have not provided us with your email address. Please use another authentication provider or use local sign-up.'
      redirect_to new_user_session_path
    end

  end


  def new_with_omniauth
    email = params[:user][:email]
    name = params[:user][:name]
    password = params[:user][:password]
    @provider = params[:provider]
    @uid = params[:uid]

    @user = User.find_by_email(email)
    if @user
      if @user.valid_password?(password)
        @user.omniauth_identities.create(:provider => @provider, :uid => @uid)
        flash[:notice] = 'Sign in via ' + PROVIDERS[@provider] + ' has been added to your account. Signed in successfully!'
        sign_in_and_redirect(:user, @user)
      else
        @user = User.new(name:name, email:email)
        flash[:error] = 'Password incorrect!'
        render 'devise/registrations/new_with_omniauth'
      end
    else
      @user = User.new(name: name, email: email, password: password, password_confirmation: password)
      if @user.save
        @user.omniauth_identities.create(:provider => @provider, :uid => @uid)
        flash[:notice] = 'Your account has been created via ' + PROVIDERS[@provider] + '. In your profile you can change your personal information and amend your local password from the one we have randomly generated for you.'
        sign_in_and_redirect(:user, @user)
      else
        render 'devise/registrations/new_with_omniauth'
      end
    end
  end


private

  def allowed_omniauth_identity_params
    params.require(:omniauth_identity).permit(:user_id, :provider, :uid)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate_user!

	  def index
	    @users = User.all
	  end

	  def show
	  	user_id = params[:id] || current_user.id
	    @user = User.find(user_id)
	  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/establishments/index.html.erb
<h1>Establishments#index</h1>
<p>Find me in app/views/establishments/index.html.erb</p>

app/views/establishments/show.html.erb
<h1>Establishments#show</h1>
<p>Find me in app/views/establishments/show.html.erb</p>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="navbar">

  <% if user_signed_in? %>
    <%= link_to "Takeout-Terror", user_root_path, :class => 'navbar-brand' %>
  <% else %>
    <%= link_to "Takeout-Terror", root_path, :class => 'navbar-brand' %>
  <% end %>

  <ul class="nav navbar-nav">
    <% if user_signed_in? %>
      <li>
      <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
      </li>
    <% else %>
      <li>
      <%= link_to 'Login', new_user_session_path %>
      </li>
    <% end %>
    <% if user_signed_in? %>
      <li>
      <%= link_to 'Edit account', edit_user_registration_path %>
      </li>
    <% else %>
      <li>
      <%= link_to 'Sign up', new_user_registration_path %>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TakeoutTerror</title>
  <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=AIzaSyCxKWONNuzbrvy_S_2HzBZnasiS0c1ZG1E&sensor=false"></script>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<header>
			<%= render 'layouts/navigation' %>
			<%= render 'layouts/messages' %>
	</header>

	<div>
		<%= yield %>
	</div>

</div>
</body>
</html>

app/views/locations/_map.html.erb
<h4>Here's the map</h4>

<div id="map"></div>

<button onclick="getLocation()">Try It</button>

app/views/locations/initial_home.html.erb
<h3>Home</h3>

app/views/users/index.html.erb
<ul>
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %> signed up <%= user.created_at.to_date %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>